In [15]:
import numpy as np

In [16]:
lst = [1,2,3,4,5]

ho = np.array(lst)

In [17]:
ho

array([1, 2, 3, 4, 5])

In [11]:
list1 = [1,2,3,4,5]
list2 = [2,3,4,5,6]
list3 = [4,5,6,7,8]

hi = np.array([list1,list2,list3])

In [12]:
hi

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [20]:
hi.shape

(3, 5)

In [18]:
type(ho)

numpy.ndarray

In [21]:
ho.shape

(5,)

In [22]:
## indexing...............
ho

array([1, 2, 3, 4, 5])

In [23]:
ho[3]

4

In [24]:
ho[:]    ## iska mean sara array print kar do 

array([1, 2, 3, 4, 5])

In [27]:
ho[::]   ## iska means bhi sara array print kar do

array([1, 2, 3, 4, 5])

In [28]:
ho[:-1]   ## iska matlab last wale ko chod do baki sab ko print kar do 

array([1, 2, 3, 4])

In [29]:
ho[-1:]   ## iska matlab sirf last wala baki sab ki ma ki chut

array([5])

In [31]:
ho[1:]    ## means 1 ko chod do baki sab ko le lo 

array([2, 3, 4, 5])

In [32]:
ho[:1]   ## 1 ko print kar do baki sab ko chod do 

array([1])

In [33]:
ho[:2]    ## means oth index wala orr 1st index wale ko print kar do 

array([1, 2])

In [37]:
ho[::3]   ### start ko leke or 3  element jump karke print kar dega  orr ese hi chalta rhega 

array([1, 4])

In [38]:
ho[::-3]    ## is bar last ka element leke fir 3 jump karke agla element print karega

array([5, 2])

In [39]:
## indexing for multidimentional
hi

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [111]:
hi[:,-5]  ## iska matlab hai sari row me se 1st column ko print kar de

array([1, 2, 4])

In [46]:
hi[2,:] 

array([4, 5, 6, 7, 8])

In [47]:
hi[1:,1:3]

array([[3, 4],
       [5, 6]])

In [125]:
hi[:3,-5:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [126]:
## EDA .....

In [127]:
hi

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [128]:
hi<2

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [129]:
hi[hi<2]

array([1])

In [130]:
hi.shape

(3, 5)

In [131]:
hi

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [132]:
hi.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 4, 5],
       [6, 7, 8]])

In [133]:
## mechanism to create an array ...

np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [135]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [141]:
hi

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [142]:
hi*hi

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [16, 25, 36, 49, 64]])

In [139]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [140]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [145]:
## to inisialize randon numbers we use random.randint() function

np.random.randint(10,50)

34

In [151]:
np.random.randint(10,50,6)

array([38, 29, 21, 35, 44, 43])

In [157]:
np.random.randint(10,50,6).reshape(2,3)

array([[31, 17, 35],
       [11, 16, 10]])

In [158]:
np.random.random_sample((4,7))  ## (4,7) ka array bana dega or sari value 0-1 ke bich me inisialise kar dega apne aap 

array([[0.12462427, 0.04839003, 0.83618685, 0.82465883, 0.33036331,
        0.87276146, 0.90284978],
       [0.13550477, 0.46398397, 0.88711746, 0.98865142, 0.80429199,
        0.63923478, 0.53327254],
       [0.48285541, 0.48149504, 0.33008673, 0.31332719, 0.78507476,
        0.00170399, 0.85732862],
       [0.06847541, 0.05116941, 0.56001309, 0.19564989, 0.8519842 ,
        0.4786164 , 0.69483736]])